# coding: utf-8

"""
    API Employment Verification Sandbox

    This API lets you verify a person employment status. If a person has a job it also returns the industrial sector and the industry COVID risk segment.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: api@circulodecredito.com.mx
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EmploymentVerificationId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'employment_verification_request_id': 'str',
        'subscription_id': 'str',
        'inquiry_id': 'str'
    }

    attribute_map = {
        'employment_verification_request_id': 'employmentVerificationRequestId',
        'subscription_id': 'subscriptionId',
        'inquiry_id': 'inquiryId'
    }

    def __init__(self, employment_verification_request_id=None, subscription_id=None, inquiry_id=None):  # noqa: E501
        """EmploymentVerificationId - a model defined in Swagger"""  # noqa: E501

        self._employment_verification_request_id = None
        self._subscription_id = None
        self._inquiry_id = None
        self.discriminator = None

        if employment_verification_request_id is not None:
            self.employment_verification_request_id = employment_verification_request_id
        if subscription_id is not None:
            self.subscription_id = subscription_id
        if inquiry_id is not None:
            self.inquiry_id = inquiry_id

    @property
    def employment_verification_request_id(self):
        """Gets the employment_verification_request_id of this EmploymentVerificationId.  # noqa: E501

        The identifier of the employment verification request given by the API consumer (UUID).  # noqa: E501

        :return: The employment_verification_request_id of this EmploymentVerificationId.  # noqa: E501
        :rtype: str
        """
        return self._employment_verification_request_id

    @employment_verification_request_id.setter
    def employment_verification_request_id(self, employment_verification_request_id):
        """Sets the employment_verification_request_id of this EmploymentVerificationId.

        The identifier of the employment verification request given by the API consumer (UUID).  # noqa: E501

        :param employment_verification_request_id: The employment_verification_request_id of this EmploymentVerificationId.  # noqa: E501
        :type: str
        """

        self._employment_verification_request_id = employment_verification_request_id

    @property
    def subscription_id(self):
        """Gets the subscription_id of this EmploymentVerificationId.  # noqa: E501

        The API Hub event subscription identifier (UUID).  # noqa: E501

        :return: The subscription_id of this EmploymentVerificationId.  # noqa: E501
        :rtype: str
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id):
        """Sets the subscription_id of this EmploymentVerificationId.

        The API Hub event subscription identifier (UUID).  # noqa: E501

        :param subscription_id: The subscription_id of this EmploymentVerificationId.  # noqa: E501
        :type: str
        """

        self._subscription_id = subscription_id

    @property
    def inquiry_id(self):
        """Gets the inquiry_id of this EmploymentVerificationId.  # noqa: E501

        The employment verification process identifier given by Círculo de Crédito.  # noqa: E501

        :return: The inquiry_id of this EmploymentVerificationId.  # noqa: E501
        :rtype: str
        """
        return self._inquiry_id

    @inquiry_id.setter
    def inquiry_id(self, inquiry_id):
        """Sets the inquiry_id of this EmploymentVerificationId.

        The employment verification process identifier given by Círculo de Crédito.  # noqa: E501

        :param inquiry_id: The inquiry_id of this EmploymentVerificationId.  # noqa: E501
        :type: str
        """

        self._inquiry_id = inquiry_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmploymentVerificationId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmploymentVerificationId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
